version: '3.8'
services:
  #################################
  # SERVICE APP SERVER ENVIRONMENT
  ################################
  app_server:
    build: .
    restart: always
    env_file: .env
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - database
    networks:
      - mern_network
  #################################
  # SERVICE APP CLIENT ENVIRONMENT
  ################################
  app_client:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    env_file: client/.env
    ports:
      - 3000:3000
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    depends_on:
      - app_server
    networks:
      - mern_network
  ##########################
  # SERVICE DB ENVIRONMENT
  ##########################
  database:
    image: mysql:latest
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - mern_network
  ##########################
  # VOLUMES PERSISTENT DATA
  ##########################
volumes:
  database:
  #############################
  # NETWORKS SHARING CONNECTION
  #############################
networks:
  mern_network:
